name: AnimalsControl
version: '${version}'
main: com.github.cinnaio.animalscontrol.AnimalsControl
api-version: '1.21'
api: '1.21'
description: '控制动物繁殖和成长的插件'

commands:
  animalcontrol:
    description: '动物控制插件的命令'
    usage: '/animalcontrol <reload|toggle>'
    permission: animalscontrol.reload
  acreload:
    description: '重载插件配置'
    usage: '/acreload'
    permission: animalscontrol.reload
  toggleRemainingTime:
    description: '切换显示剩余时间'
    usage: '/toggleRemainingTime'
    permission: animalscontrol.toggleRemainingTime

permissions:
  animalscontrol.reload:
    description: '重载插件配置的权限'
    default: op
  animalscontrol.toggleRemainingTime:
    description: '切换显示剩余时间的权限'
    default: true
